/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LessonId = IDL.Nat;
export const CertificateId = IDL.Text;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const CertificateLevel = IDL.Variant({
  'HigherLevel' : IDL.Null,
  'StandardLevel' : IDL.Null,
});
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'completedAt' : Timestamp,
  'userId' : UserId,
  'level' : CertificateLevel,
  'learnerName' : IDL.Text,
  'issuedAt' : Timestamp,
  'courseTitle' : IDL.Text,
});
export const CourseOverview = IDL.Record({
  'title' : IDL.Text,
  'totalLessons' : IDL.Nat,
  'description' : IDL.Text,
  'totalModules' : IDL.Nat,
  'estimatedHours' : IDL.Nat,
});
export const ModuleId = IDL.Nat;
export const DashboardData = IDL.Record({
  'totalLessons' : IDL.Nat,
  'completionPercentage' : IDL.Nat,
  'completedLessons' : IDL.Nat,
  'nextLessonId' : IDL.Opt(LessonId),
  'currentModuleId' : IDL.Opt(ModuleId),
});
export const Difficulty = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : LessonId,
  'moduleId' : ModuleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'isHL' : IDL.Bool,
  'difficulty' : Difficulty,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
});
export const LessonWithStatus = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'completed' : IDL.Bool,
  'lesson' : Lesson,
});
export const Module = IDL.Record({
  'id' : ModuleId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
});
export const ModuleWithLessons = IDL.Record({
  'totalCount' : IDL.Nat,
  'completedCount' : IDL.Nat,
  'lessons' : IDL.Vec(LessonWithStatus),
  'module' : Module,
});
export const UserProfile = IDL.Record({
  'userId' : UserId,
  'overallProgressPercentage' : IDL.Nat,
  'isEnrolled' : IDL.Bool,
  'certificates' : IDL.Vec(Certificate),
});

export const idlService = IDL.Service({
  'completeLesson' : IDL.Func(
      [LessonId, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'err' : IDL.Text,
          'certificateIssued' : Certificate,
        }),
      ],
      [],
    ),
  'enrollInCourse' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getCertificate' : IDL.Func([], [IDL.Opt(Certificate)], ['query']),
  'getCourseOverview' : IDL.Func([], [CourseOverview], ['query']),
  'getDashboard' : IDL.Func([], [IDL.Opt(DashboardData)], ['query']),
  'getModulesWithStatus' : IDL.Func(
      [],
      [IDL.Vec(ModuleWithLessons)],
      ['query'],
    ),
  'getProgressHistory' : IDL.Func([], [IDL.Vec(LessonWithStatus)], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LessonId = IDL.Nat;
  const CertificateId = IDL.Text;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const CertificateLevel = IDL.Variant({
    'HigherLevel' : IDL.Null,
    'StandardLevel' : IDL.Null,
  });
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'completedAt' : Timestamp,
    'userId' : UserId,
    'level' : CertificateLevel,
    'learnerName' : IDL.Text,
    'issuedAt' : Timestamp,
    'courseTitle' : IDL.Text,
  });
  const CourseOverview = IDL.Record({
    'title' : IDL.Text,
    'totalLessons' : IDL.Nat,
    'description' : IDL.Text,
    'totalModules' : IDL.Nat,
    'estimatedHours' : IDL.Nat,
  });
  const ModuleId = IDL.Nat;
  const DashboardData = IDL.Record({
    'totalLessons' : IDL.Nat,
    'completionPercentage' : IDL.Nat,
    'completedLessons' : IDL.Nat,
    'nextLessonId' : IDL.Opt(LessonId),
    'currentModuleId' : IDL.Opt(ModuleId),
  });
  const Difficulty = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : LessonId,
    'moduleId' : ModuleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'isHL' : IDL.Bool,
    'difficulty' : Difficulty,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
  });
  const LessonWithStatus = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'completed' : IDL.Bool,
    'lesson' : Lesson,
  });
  const Module = IDL.Record({
    'id' : ModuleId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
  });
  const ModuleWithLessons = IDL.Record({
    'totalCount' : IDL.Nat,
    'completedCount' : IDL.Nat,
    'lessons' : IDL.Vec(LessonWithStatus),
    'module' : Module,
  });
  const UserProfile = IDL.Record({
    'userId' : UserId,
    'overallProgressPercentage' : IDL.Nat,
    'isEnrolled' : IDL.Bool,
    'certificates' : IDL.Vec(Certificate),
  });
  
  return IDL.Service({
    'completeLesson' : IDL.Func(
        [LessonId, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'err' : IDL.Text,
            'certificateIssued' : Certificate,
          }),
        ],
        [],
      ),
    'enrollInCourse' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getCertificate' : IDL.Func([], [IDL.Opt(Certificate)], ['query']),
    'getCourseOverview' : IDL.Func([], [CourseOverview], ['query']),
    'getDashboard' : IDL.Func([], [IDL.Opt(DashboardData)], ['query']),
    'getModulesWithStatus' : IDL.Func(
        [],
        [IDL.Vec(ModuleWithLessons)],
        ['query'],
      ),
    'getProgressHistory' : IDL.Func([], [IDL.Vec(LessonWithStatus)], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };