/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate {
  'id' : CertificateId,
  'completedAt' : Timestamp,
  'userId' : UserId,
  'level' : CertificateLevel,
  'learnerName' : string,
  'issuedAt' : Timestamp,
  'courseTitle' : string,
}
export type CertificateId = string;
export type CertificateLevel = { 'HigherLevel' : null } |
  { 'StandardLevel' : null };
export interface CourseOverview {
  'title' : string,
  'totalLessons' : bigint,
  'description' : string,
  'totalModules' : bigint,
  'estimatedHours' : bigint,
}
export interface DashboardData {
  'totalLessons' : bigint,
  'completionPercentage' : bigint,
  'completedLessons' : bigint,
  'nextLessonId' : [] | [LessonId],
  'currentModuleId' : [] | [ModuleId],
}
export type Difficulty = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface Lesson {
  'id' : LessonId,
  'moduleId' : ModuleId,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'isHL' : boolean,
  'difficulty' : Difficulty,
  'description' : string,
  'durationMinutes' : bigint,
}
export type LessonId = bigint;
export interface LessonWithStatus {
  'completedAt' : [] | [Timestamp],
  'completed' : boolean,
  'lesson' : Lesson,
}
export interface Module {
  'id' : ModuleId,
  'title' : string,
  'order' : bigint,
  'description' : string,
}
export type ModuleId = bigint;
export interface ModuleWithLessons {
  'totalCount' : bigint,
  'completedCount' : bigint,
  'lessons' : Array<LessonWithStatus>,
  'module' : Module,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'userId' : UserId,
  'overallProgressPercentage' : bigint,
  'isEnrolled' : boolean,
  'certificates' : Array<Certificate>,
}
export interface _SERVICE {
  'completeLesson' : ActorMethod<
    [LessonId, string],
    { 'ok' : null } |
      { 'err' : string } |
      { 'certificateIssued' : Certificate }
  >,
  'enrollInCourse' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'getCertificate' : ActorMethod<[], [] | [Certificate]>,
  'getCourseOverview' : ActorMethod<[], CourseOverview>,
  'getDashboard' : ActorMethod<[], [] | [DashboardData]>,
  'getModulesWithStatus' : ActorMethod<[], Array<ModuleWithLessons>>,
  'getProgressHistory' : ActorMethod<[], Array<LessonWithStatus>>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];