/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ModuleId = bigint;
export type Timestamp = bigint;
export interface DashboardData {
    totalLessons: bigint;
    completionPercentage: bigint;
    completedLessons: bigint;
    nextLessonId?: LessonId;
    currentModuleId?: ModuleId;
}
export type LessonId = bigint;
export interface CourseOverview {
    title: string;
    totalLessons: bigint;
    description: string;
    totalModules: bigint;
    estimatedHours: bigint;
}
export type CertificateId = string;
export type UserId = Principal;
export interface ModuleWithLessons {
    totalCount: bigint;
    completedCount: bigint;
    lessons: Array<LessonWithStatus>;
    module: Module;
}
export interface Lesson {
    id: LessonId;
    moduleId: ModuleId;
    title: string;
    content: string;
    order: bigint;
    isHL: boolean;
    difficulty: Difficulty;
    description: string;
    durationMinutes: bigint;
}
export interface LessonWithStatus {
    completedAt?: Timestamp;
    completed: boolean;
    lesson: Lesson;
}
export interface Module {
    id: ModuleId;
    title: string;
    order: bigint;
    description: string;
}
export interface UserProfile {
    userId: UserId;
    overallProgressPercentage: bigint;
    isEnrolled: boolean;
    certificates: Array<Certificate>;
}
export interface Certificate {
    id: CertificateId;
    completedAt: Timestamp;
    userId: UserId;
    level: CertificateLevel;
    learnerName: string;
    issuedAt: Timestamp;
    courseTitle: string;
}
export enum CertificateLevel {
    HigherLevel = "HigherLevel",
    StandardLevel = "StandardLevel"
}
export enum Difficulty {
    Beginner = "Beginner",
    Advanced = "Advanced",
    Intermediate = "Intermediate"
}
export interface backendInterface {
    completeLesson(lessonId: LessonId, learnerName: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    } | {
        __kind__: "certificateIssued";
        certificateIssued: Certificate;
    }>;
    enrollInCourse(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCertificate(): Promise<Certificate | null>;
    getCourseOverview(): Promise<CourseOverview>;
    getDashboard(): Promise<DashboardData | null>;
    getModulesWithStatus(): Promise<Array<ModuleWithLessons>>;
    getProgressHistory(): Promise<Array<LessonWithStatus>>;
    getUserProfile(): Promise<UserProfile>;
}
import type { Certificate as _Certificate, CertificateId as _CertificateId, CertificateLevel as _CertificateLevel, DashboardData as _DashboardData, Difficulty as _Difficulty, Lesson as _Lesson, LessonId as _LessonId, LessonWithStatus as _LessonWithStatus, Module as _Module, ModuleId as _ModuleId, ModuleWithLessons as _ModuleWithLessons, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeLesson(arg0: LessonId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    } | {
        __kind__: "certificateIssued";
        certificateIssued: Certificate;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async enrollInCourse(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse();
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse();
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificate(): Promise<Certificate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificate();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificate();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseOverview(): Promise<CourseOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseOverview();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseOverview();
            return result;
        }
    }
    async getDashboard(): Promise<DashboardData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModulesWithStatus(): Promise<Array<ModuleWithLessons>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModulesWithStatus();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModulesWithStatus();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressHistory(): Promise<Array<LessonWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressHistory();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressHistory();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CertificateLevel_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CertificateLevel): CertificateLevel {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Certificate_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Certificate): Certificate {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardData_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardData): DashboardData {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_LessonWithStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonWithStatus): LessonWithStatus {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ModuleWithLessons_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleWithLessons): ModuleWithLessons {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LessonId]): LessonId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ModuleId]): ModuleId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Certificate]): Certificate | null {
    return value.length === 0 ? null : from_candid_Certificate_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DashboardData]): DashboardData | null {
    return value.length === 0 ? null : from_candid_DashboardData_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalLessons: bigint;
    completionPercentage: bigint;
    completedLessons: bigint;
    nextLessonId: [] | [_LessonId];
    currentModuleId: [] | [_ModuleId];
}): {
    totalLessons: bigint;
    completionPercentage: bigint;
    completedLessons: bigint;
    nextLessonId?: LessonId;
    currentModuleId?: ModuleId;
} {
    return {
        totalLessons: value.totalLessons,
        completionPercentage: value.completionPercentage,
        completedLessons: value.completedLessons,
        nextLessonId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.nextLessonId)),
        currentModuleId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.currentModuleId))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    completedCount: bigint;
    lessons: Array<_LessonWithStatus>;
    module: _Module;
}): {
    totalCount: bigint;
    completedCount: bigint;
    lessons: Array<LessonWithStatus>;
    module: Module;
} {
    return {
        totalCount: value.totalCount,
        completedCount: value.completedCount,
        lessons: from_candid_vec_n16(_uploadFile, _downloadFile, value.lessons),
        module: value.module
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: [] | [_Timestamp];
    completed: boolean;
    lesson: _Lesson;
}): {
    completedAt?: Timestamp;
    completed: boolean;
    lesson: Lesson;
} {
    return {
        completedAt: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.completedAt)),
        completed: value.completed,
        lesson: from_candid_Lesson_n20(_uploadFile, _downloadFile, value.lesson)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LessonId;
    moduleId: _ModuleId;
    title: string;
    content: string;
    order: bigint;
    isHL: boolean;
    difficulty: _Difficulty;
    description: string;
    durationMinutes: bigint;
}): {
    id: LessonId;
    moduleId: ModuleId;
    title: string;
    content: string;
    order: bigint;
    isHL: boolean;
    difficulty: Difficulty;
    description: string;
    durationMinutes: bigint;
} {
    return {
        id: value.id,
        moduleId: value.moduleId,
        title: value.title,
        content: value.content,
        order: value.order,
        isHL: value.isHL,
        difficulty: from_candid_Difficulty_n22(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        durationMinutes: value.durationMinutes
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    overallProgressPercentage: bigint;
    isEnrolled: boolean;
    certificates: Array<_Certificate>;
}): {
    userId: UserId;
    overallProgressPercentage: bigint;
    isEnrolled: boolean;
    certificates: Array<Certificate>;
} {
    return {
        userId: value.userId,
        overallProgressPercentage: value.overallProgressPercentage,
        isEnrolled: value.isEnrolled,
        certificates: from_candid_vec_n26(_uploadFile, _downloadFile, value.certificates)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CertificateId;
    completedAt: _Timestamp;
    userId: _UserId;
    level: _CertificateLevel;
    learnerName: string;
    issuedAt: _Timestamp;
    courseTitle: string;
}): {
    id: CertificateId;
    completedAt: Timestamp;
    userId: UserId;
    level: CertificateLevel;
    learnerName: string;
    issuedAt: Timestamp;
    courseTitle: string;
} {
    return {
        id: value.id,
        completedAt: value.completedAt,
        userId: value.userId,
        level: from_candid_CertificateLevel_n4(_uploadFile, _downloadFile, value.level),
        learnerName: value.learnerName,
        issuedAt: value.issuedAt,
        courseTitle: value.courseTitle
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
} | {
    certificateIssued: _Certificate;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "certificateIssued";
    certificateIssued: Certificate;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "certificateIssued" in value ? {
        __kind__: "certificateIssued",
        certificateIssued: from_candid_Certificate_n2(_uploadFile, _downloadFile, value.certificateIssued)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
}): Difficulty {
    return "Beginner" in value ? Difficulty.Beginner : "Advanced" in value ? Difficulty.Advanced : "Intermediate" in value ? Difficulty.Intermediate : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HigherLevel: null;
} | {
    StandardLevel: null;
}): CertificateLevel {
    return "HigherLevel" in value ? CertificateLevel.HigherLevel : "StandardLevel" in value ? CertificateLevel.StandardLevel : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModuleWithLessons>): Array<ModuleWithLessons> {
    return value.map((x)=>from_candid_ModuleWithLessons_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LessonWithStatus>): Array<LessonWithStatus> {
    return value.map((x)=>from_candid_LessonWithStatus_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Certificate>): Array<Certificate> {
    return value.map((x)=>from_candid_Certificate_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
